
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/article_comment_data?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
#    username: root
#    password: gan57124
#    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9100


spring:



  datasource:
    url: jdbc:mysql://192.168.3.5:3306/article_comment_data_test?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=CTT #注意设置编码格式 #url
    username: gty #用户名
    password: gty1qaz@WSX #密码
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库链接驱动

  mvc:
    hiddenmethod:
      filter:
        enabled: true

#  security:
#    user:
#      name: ganty
#      password: 123123


mybatis:
  mapper-locations: classpath:com/wake/nlkm/mapper/xml/*.xml
  type-aliases-package: com.wake.nlkm.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    learning: debug
  file:
    path: logs/nlkm.log